version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: todo_app
      DB_PORT: 3306

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      # This is for build-time injection (React requires REACT_APP_ prefix)
      REACT_APP_API_URL: http://localhost:8080
    depends_on:
      - backend

volumes:
  mysql_data: